export enum SessionStatus {
  AWAITING_BIO = 'AWAITING_BIO',
  SELECTING_SPREAD = 'SELECTING_SPREAD',
  SHUFFLING = 'SHUFFLING',
  PICKING = 'PICKING',
  INTERPRETING = 'INTERPRETING',
  FREE_CHAT = 'FREE_CHAT',
}
