import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#090712',
  },
  screen: {
    flex: 1,
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  kicker: {
    color: '#7df9ff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#fff6d6',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statusPill: {
    borderColor: '#423952',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  statusText: {
    color: '#ff4fd8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
  },
  languageToggle: {
    borderColor: '#332b42',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  languageToggleText: {
    color: '#7df9ff',
    fontSize: 11,
    fontWeight: '800',
  },
  apiPanel: {
    gap: 6,
  },
  label: {
    color: '#a8a0b9',
    fontSize: 12,
    fontWeight: '700',
  },
  apiInput: {
    backgroundColor: '#15101f',
    borderColor: '#332b42',
    borderRadius: 8,
    borderWidth: 1,
    color: '#fff7e8',
    fontSize: 13,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  cardRail: {
    flexDirection: 'row',
    gap: 8,
    height: 116,
    overflow: 'hidden',
  },
  previewCard: {
    aspectRatio: 0.62,
    borderColor: '#302345',
    borderRadius: 8,
    borderWidth: 1,
    height: 104,
  },
  previewCardHigh: {
    marginTop: 10,
  },
  spreadRow: {
    flexDirection: 'row',
    gap: 8,
  },
  spreadButton: {
    backgroundColor: '#15101f',
    borderColor: '#342842',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 96,
    padding: 10,
    justifyContent: 'space-between',
  },
  spreadActive: {
    backgroundColor: '#241032',
    borderColor: '#ff4fd8',
  },
  spreadTitle: {
    color: '#fff7e8',
    fontSize: 13,
    fontWeight: '800',
  },
  spreadTextActive: {
    color: '#7df9ff',
  },
  spreadPositions: {
    color: '#a8a0b9',
    fontSize: 11,
    fontWeight: '700',
  },
  spreadSubtitle: {
    color: '#d6caef',
    fontSize: 10,
    lineHeight: 13,
    marginTop: 4,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#7df9ff',
    borderRadius: 8,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#10051e',
    fontSize: 14,
    fontWeight: '900',
  },
  buttonPressed: {
    opacity: 0.72,
  },
  buttonDisabled: {
    opacity: 0.64,
  },
  chatPanel: {
    backgroundColor: '#100c18',
    borderColor: '#30283d',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 260,
    overflow: 'hidden',
  },
  spreadBoard: {
    backgroundColor: '#100c18',
    borderColor: '#30283d',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  spreadHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    color: '#7df9ff',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  spreadStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  spreadStatusText: {
    color: '#d6caef',
    fontSize: 11,
    fontWeight: '700',
  },
  spreadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  spreadEmpty: {
    color: '#a8a0b9',
    fontSize: 12,
  },
  spreadCard: {
    gap: 6,
    width: '30%',
  },
  spreadCardImage: {
    borderColor: '#302345',
    borderRadius: 8,
    borderWidth: 1,
    height: 120,
    width: '100%',
  },
  spreadCardFallback: {
    alignItems: 'center',
    backgroundColor: '#171120',
    borderColor: '#302345',
    borderRadius: 8,
    borderWidth: 1,
    height: 120,
    justifyContent: 'center',
    width: '100%',
  },
  spreadCardFallbackText: {
    color: '#fff7e8',
    fontWeight: '800',
  },
  spreadCardLabel: {
    color: '#d6caef',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatContent: {
    gap: 10,
    padding: 12,
  },
  messageBubble: {
    borderRadius: 8,
    maxWidth: '88%',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#1a1424',
    borderColor: '#332642',
    borderWidth: 1,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#2b1238',
    borderColor: '#ff4fd8',
    borderWidth: 1,
  },
  messageRole: {
    color: '#7df9ff',
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  messageText: {
    color: '#fff7e8',
    fontSize: 14,
    lineHeight: 20,
  },
  typingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  typingText: {
    color: '#d6caef',
    fontSize: 13,
  },
  errorText: {
    color: '#ffb3a7',
    fontSize: 12,
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  composer: {
    alignItems: 'flex-end',
    borderColor: '#30283d',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    padding: 10,
  },
  composerInput: {
    backgroundColor: '#171120',
    borderColor: '#342842',
    borderRadius: 8,
    borderWidth: 1,
    color: '#fff7e8',
    flex: 1,
    fontSize: 14,
    maxHeight: 96,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: '#ff4fd8',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sendDisabled: {
    backgroundColor: '#3a3045',
  },
  sendButtonText: {
    color: '#120414',
    fontSize: 13,
    fontWeight: '900',
  },
  spreadScreenHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 8,
  },
  spreadScreenTitle: {
    color: '#fff7e8',
    fontSize: 22,
    fontWeight: '800',
  },
  spreadScreenSubtitle: {
    color: '#d6caef',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  spreadScreenDescription: {
    color: '#a8a0b9',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
    marginTop: 6,
    maxWidth: 320,
  },
  spreadCloseButton: {
    borderColor: '#423952',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  spreadCloseText: {
    color: '#ff4fd8',
    fontSize: 12,
    fontWeight: '800',
  },
  spreadScreenControls: {
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  deckInfo: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  deckCard: {
    alignItems: 'center',
    backgroundColor: '#1a1424',
    borderColor: '#332642',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  deckCardText: {
    color: '#a8a0b9',
    fontSize: 11,
    fontWeight: '700',
  },
  deckCardCount: {
    color: '#fff7e8',
    fontSize: 16,
    fontWeight: '800',
  },
  deckHint: {
    color: '#d6caef',
    fontSize: 12,
    fontWeight: '600',
  },
  spreadLayoutCard: {
    flex: 1,
    paddingHorizontal: 18,
    paddingBottom: 20,
  },
  spreadLayoutImage: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
  },
  spreadPosition: {
    alignItems: 'center',
    height: 70,
    justifyContent: 'center',
    position: 'absolute',
    transform: [{ translateX: -35 }, { translateY: -45 }],
    width: 60,
  },
  spreadPositionPressed: {
    opacity: 0.7,
  },
  spreadPositionPlaceholder: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 12, 24, 0.85)',
    borderColor: '#7df9ff',
    borderRadius: 8,
    borderWidth: 1,
    height: 90,
    justifyContent: 'center',
    width: 60,
  },
  spreadPositionLabel: {
    color: '#7df9ff',
    fontSize: 12,
    fontWeight: '800',
  },
  spreadPositionCardId: {
    color: '#fff7e8',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  spreadPositionImage: {
    borderColor: '#302345',
    borderRadius: 8,
    borderWidth: 1,
    height: 90,
    width: 60,
  },
  spreadWireframeContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  spreadWireframeCircle: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderRadius: 999,
    borderWidth: 2,
    height: '70%',
    left: '15%',
    position: 'absolute',
    top: '15%',
    width: '70%',
  },
  spreadWireframeCrossVertical: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderWidth: 2,
    height: '65%',
    left: '28%',
    position: 'absolute',
    top: '17%',
    width: 0,
  },
  spreadWireframeCrossHorizontal: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderWidth: 2,
    height: 0,
    left: '14%',
    position: 'absolute',
    top: '48%',
    width: '40%',
  },
  spreadWireframeColumn: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderWidth: 2,
    height: '60%',
    left: '72%',
    position: 'absolute',
    top: '20%',
    width: 0,
  },
  spreadWireframeRow: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderWidth: 2,
    height: 0,
    left: '12%',
    position: 'absolute',
    top: '38%',
    width: '76%',
  },
  spreadWireframeRowBottom: {
    borderColor: 'rgba(125, 249, 255, 0.35)',
    borderWidth: 2,
    height: 0,
    left: '12%',
    position: 'absolute',
    top: '70%',
    width: '76%',
  },
});

export default styles;
